### ISSUE TITLE
Array datatypes cause errors

### ISSUE THREAD

**Issue by FrostyFitz** [Ward727a/godot_datatable_plugin#9]
I've made a simple structure and tried to use array option for both an integer or a string. The following is a snippet from my table structure:
![image](https://github.com/Ward727a/godot_datatable_plugin/assets/59144531/d761ee23-5a9e-49db-8394-74bda160da6c)
When I go to my table and attempt to enter data in the array field it initially looks like it works, but the data in the array field never gets saved. Upon closer inspection it looks like the following error appears in output every time you attempt to edit an item in the table:
 res://addons/datatable_godot/ui/schema/new_table/VBC_itemTableDataList.gd:59 - Invalid get index 'default' (on base: 'Dictionary').

Unsure of how to proceed, or if I am doing something wrong. 
**Desktop:**
 - OS: MacOS

**Godot information**
- Version: 4.2
- Plugin version: 2.2.0
- Language used: GDScript

**Additional context**

**Comment by Ward727a** [comment]
Hey :)

After checking the code, it appears that it's because I forgot to check something, so what you can do to fix this are :
- Wait for the v2.3.0 to release (I can't say for sure when it will release)
- Or you can add these line in the file : 
"res://addons/datatable_godot/ui/schema/new_table/VBC_itemTableDataList.gd" on the line 58:
```
if !structure['params'][key].has('default'):
	structure['params'][key]['default'] = null
```
Like this:
![image](https://github.com/Ward727a/godot_datatable_plugin/assets/50712170/cb4cd24e-7a39-4e00-a056-ac1ad2ab8ddc)

Sorry for the problem, and hope it work now =)

**Comment by FrostyFitz** [comment]
Thanks!!

**Comment by FrostyFitz** [comment]
Hey I tested this out today and it works great. Thanks for the fast response!
